language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database "my-watched-movies-test";' -U postgres

script:
  - mvn liquibase:update -Dproject.environment=test
  - mvn -B verify sonar:sonar -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN