language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database "my-watched-movies-test";' -U postgres